version: "3.8"

services:
  api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    depends_on:
      - redis
      - evolution-postgres
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    # Coolify proxy, HTTPS, and certificate via Traefik
    labels:
        - traefik.enable=true
  # HTTPS router
        - traefik.http.routers.evoapi_https.rule=Host(`evoapi.growthgrid.me`)
        - traefik.http.routers.evoapi_https.entryPoints=websecure
        - traefik.http.routers.evoapi_https.tls=true
        - traefik.http.routers.evoapi_https.tls.certresolver=letsencrypt
        - traefik.http.services.evoapi_svc.loadbalancer.server.port=8080
        - traefik.http.routers.evoapi_https.service=evoapi_svc
  # HTTP → HTTPS redirect
        - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
        - traefik.http.routers.evoapi_http.rule=Host(`evoapi.growthgrid.me`)
        - traefik.http.routers.evoapi_http.entryPoints=web
        - traefik.http.routers.evoapi_http.middlewares=redirect-to-https

  redis:
    container_name: evolution_redis
    image: redis:latest
    restart: always
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    # Provide the alias some templates expect
    networks:
      default:
        aliases:
          - evolution-redis
    labels:
      - "traefik.enable=false"

  evolution-postgres:
    container_name: evolution_postgres
    image: postgres:15
    restart: always
    env_file:
      - .env
    command:
      - postgres
      - -c
      - max_connections=1000
      - -c
      - listen_addresses=*
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Provide the alias some templates expect
    networks:
      default:
        aliases:
          - evolution-postgres
    labels:
      - "traefik.enable=false"

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:
