services:
  api:
    image: evoapicloud/evolution-api:latest
    restart: always
    depends_on:
      - redis
      - evolution-postgres
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - default          # project's own bridge network (auto)
      - coolify          # Coolify/Traefik external proxy network

    # Runtime env for Evolution API
    environment:
      AUTHENTICATION_API_KEY: "your_long_random_key_here"
      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: "postgresql"
      # This is fine to keep; Prisma will still use host "postgres"
      DATABASE_URL: "postgresql://evolution:HSwYWENGkr6jzfHayl9ulTFAveZjBVBb4Pvs4GC3RdD5yOvbrwi8FgimvsLw5taT@postgresql-database-tswos8s0g84ks08400ggk8c0:5432/postgres"
      REDIS_URI: "redis://redis:6379"
      SERVICE_FQDN_API: "https://evoapi.growthgrid.me"
      PORT: "8080"

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"

      # Service (container internal port)
      - "traefik.http.services.evoapi-svc.loadbalancer.server.port=8080"

      # HTTPS router
      - "traefik.http.routers.evoapi-https.rule=Host(`evoapi.growthgrid.me`)"
      - "traefik.http.routers.evoapi-https.entryPoints=https"
      - "traefik.http.routers.evoapi-https.tls=true"
      - "traefik.http.routers.evoapi-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.evoapi-https.service=evoapi-svc"

      # HTTP → HTTPS redirect
      - "traefik.http.middlewares.evoapi-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.evoapi-http.rule=Host(`evoapi.growthgrid.me`)"
      - "traefik.http.routers.evoapi-http.entryPoints=http"
      - "traefik.http.routers.evoapi-http.middlewares=evoapi-redirect"
      - "traefik.http.routers.evoapi-http.service=evoapi-svc"

  redis:
    image: redis:latest
    restart: always
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    networks:
      - default
    labels:
      - "traefik.enable=false"

  evolution-postgres:
    image: postgres:15
    restart: always
    # REMOVE env_file to avoid conflicts
    # env_file:
    #   - .env
    command: ["postgres","-c","max_connections=1000","-c","listen_addresses=*"]
    environment:
      POSTGRES_DB: evolution_db
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: HSwYWENGkr6jzfHayl9ulTFAveZjBVBb4Pvs4GC3RdD5yOvbrwi8FgimvsLw5taT
    volumes:
      # >>> renamed volume so Postgres initializes fresh <<<
      - pgdata_evoapi:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - postgres
    labels:
      - "traefik.enable=false"

volumes:
  evolution_instances:
  evolution_redis:
  # >>> new volume name <<<
  pgdata_evoapi:

networks:
  coolify:
    external: true
    name: coolify
