version: "3.8"

services:
  api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    depends_on:
      - redis
      - evolution-postgres
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    labels:
      - "traefik.enable=true"

      # Service (container's internal port)
      - "traefik.http.services.evoapi-svc.loadbalancer.server.port=8080"

      # HTTPS router
      - "traefik.http.routers.evoapi-https.rule=Host(`evoapi.growthgrid.me`)"
      - "traefik.http.routers.evoapi-https.entryPoints=websecure"
      - "traefik.http.routers.evoapi-https.tls=true"
      - "traefik.http.routers.evoapi-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.evoapi-https.service=evoapi-svc"

      # HTTP → HTTPS redirect
      - "traefik.http.middlewares.evoapi-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.evoapi-http.rule=Host(`evoapi.growthgrid.me`)"
      - "traefik.http.routers.evoapi-http.entryPoints=web"
      - "traefik.http.routers.evoapi-http.middlewares=evoapi-redirect"
      - "traefik.http.routers.evoapi-http.service=evoapi-svc"

  redis:
    container_name: evolution_redis
    image: redis:latest
    restart: always
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    networks:
      default:
        aliases:
          - evolution-redis
    labels:
      - "traefik.enable=false"

  evolution-postgres:
    container_name: evolution_postgres
    image: postgres:15
    restart: always
    env_file:
      - .env
    command:
      - postgres
      - -c
      - max_connections=1000
      - -c
      - listen_addresses=*
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - evolution-postgres
    labels:
      - "traefik.enable=false"

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:
